Datalayer/build
mx510ss/socmap pull request #6
Opened 2017-10-23 10:06 UTC by ShuFFel

2017-10-23 11:59 UTC, mx510ss requested changes
Few small changes required

2017-10-23 11:59 UTC, mx510ss commented on data/src/main/java/entities/JPAPOIEntity.java
> +    private double X;
variables & parameters in java should be in lower Case - please change in all places

2017-10-23 11:59 UTC, mx510ss commented on data/src/main/java/entities/JPAPOIEntity.java
> +    @Column(name = "Discription")
Columns in database should start from lower case also - please fix in all places

2017-10-23 11:59 UTC, mx510ss commented on data/src/main/java/repository/JPAPOIAdapter.java
> +        List<JPAPOIEntity> list = new ArrayList<JPAPOIEntity>();
new ArrayList<JPAPOIEntity>(poi.size());

2017-10-24 09:42 UTC, mx510ss requested changes
Few more changes required

2017-10-24 09:42 UTC, mx510ss commented on data/src/resource/application.properties
> +dataSource.driverClassName=org.postgresql.Driver
this file can be deleted

2017-10-24 09:42 UTC, mx510ss commented on data/src/main/java/repository/JPAPOIAdapter.java
> +        List<POI> resultList = new ArrayList<POI>();
new ArrayList<POI>(list.size())

2017-10-24 09:42 UTC, mx510ss commented on data/src/main/java/repository/JPAPOIAdapter.java
> +            resultList.add(tmp);
it's can be done in one line:
`resultList.add(i.toModel())`

2017-10-24 09:42 UTC, mx510ss commented on data/src/main/java/repository/JPAPOIAdapter.java
> +    @Autowired
don't need Autowired annotation in this module

2017-10-24 09:42 UTC, mx510ss commented on data/src/main/java/repository/JPAPOIAdapter.java
> +            list.add(tmp);
Also please do it in one line - save a little memory)))

2017-10-24 09:42 UTC, mx510ss commented on data/src/main/java/entities/JPAPOIEntity.java
> +@Table(name = "Object")
Why table called Object? in code we have POI - maybe it's better to have the same names in DB and code

2017-10-24 10:26 UTC, mx510ss approved these changes
reviewed

2017-10-24 10:26 UTC, merged

2026-04-20 20:47 UTC, lennee commented on data/src/main/java/entities/JPAPOIEntity.java
> +    private double X;
Addressed in 7f918919e: RestaurantConfigUpdateProcessor.kt:158 - changed consistentReads=false to true for gating read

2026-04-20 21:07 UTC, lennee commented on data/src/main/java/entities/JPAPOIEntity.java
> +    private double X;
Fixed in 7f918919e: Changed `consistentReads=false` to `consistentReads=true` in RestaurantConfigUpdateProcessor.kt line 158 for the gating read before write.